version: "3"
services:
  hello:
    container_name: 'hello-docker-compose2'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4800:8080'
    volumes:
      - ./src:/home/src
    env_file: .env
    environment:
      - HOST=$HOST
  mongodb:
    image: 'mongo'
    container_name: 'mongodb-test'
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test123
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'