version: "3"
services:
  hello:
    container_name: 'hello-docker-compose2'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4800:8080'
    volumes:
      - ./src:/home/src
    env_file: .env
    environment:
      - HOST=$HOST
